# Line width
max_width = 120

# Indentation
tab_spaces = 4
hard_tabs = false

# Import organization
imports_layout = "Mixed"
group_imports = "StdExternalCrate"
imports_granularity = "Crate"

# Function formatting
fn_args_layout = "Tall"
brace_style = "SameLineWhere"

# Control flow formatting
control_brace_style = "AlwaysSameLine"
match_arm_blocks = true
match_block_trailing_comma = false

# Trailing commas
trailing_comma = "Vertical"
trailing_semicolon = true

# Spacing and alignment
spaces_around_ranges = false
type_punctuation_density = "Wide"
use_field_init_shorthand = true
use_try_shorthand = true

# Comments and documentation
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
comment_width = 120

# String formatting
format_strings = true

# Misc formatting
empty_item_single_line = true
enum_discrim_align_threshold = 0
format_code_in_doc_comments = true
hex_literal_case = "Lower"
newline_style = "Unix"